onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/clk
add wave -noupdate /tb/reset
add wave -noupdate -divider PC
add wave -noupdate /tb/riscv/PC_In_wire
add wave -noupdate /tb/riscv/PC_Out_wire
add wave -noupdate -divider {Instruction Parser}
add wave -noupdate /tb/riscv/Instruction_Out_wire
add wave -noupdate /tb/riscv/rs1_wire
add wave -noupdate /tb/riscv/rs2_wire
add wave -noupdate /tb/riscv/opcode_wire
add wave -noupdate /tb/riscv/clk
add wave -noupdate /tb/riscv/reset
add wave -noupdate /tb/riscv/rd_wire
add wave -noupdate /tb/riscv/ReadData1_wire
add wave -noupdate /tb/riscv/ReadData2_wire
add wave -noupdate /tb/riscv/Immediate_Data_Wire
add wave -noupdate /tb/riscv/ALU_Result_Wire
add wave -noupdate /tb/riscv/Register_WriteData_Wire
add wave -noupdate /tb/riscv/DataMemory_Read_Data
add wave -noupdate /tb/riscv/Adder1_Out_Wire
add wave -noupdate /tb/riscv/Adder2_Out_Wire
add wave -noupdate /tb/riscv/Operation_Wire
add wave -noupdate /tb/riscv/MUX_Data_Out_Wire
add wave -noupdate /tb/riscv/funct7_wire
add wave -noupdate /tb/riscv/funct3_wire
add wave -noupdate /tb/riscv/Zero_Wire
add wave -noupdate /tb/riscv/Branch_wire
add wave -noupdate /tb/riscv/MemRead_wire
add wave -noupdate /tb/riscv/MemtoReg_wire
add wave -noupdate /tb/riscv/MemWrite_wire
add wave -noupdate /tb/riscv/ALUSrc_wire
add wave -noupdate /tb/riscv/RegWrite_wire
add wave -noupdate /tb/riscv/ALUOp_wire
add wave -noupdate /tb/riscv/PC/clk
add wave -noupdate /tb/riscv/PC/reset
add wave -noupdate /tb/riscv/PC/PC_In
add wave -noupdate /tb/riscv/PC/PC_Out
add wave -noupdate /tb/riscv/Adder1/a
add wave -noupdate /tb/riscv/Adder1/b
add wave -noupdate /tb/riscv/Adder1/out
add wave -noupdate /tb/riscv/Adder2/a
add wave -noupdate /tb/riscv/Adder2/b
add wave -noupdate /tb/riscv/Adder2/out
add wave -noupdate /tb/riscv/Mux1/sel
add wave -noupdate /tb/riscv/Mux1/a
add wave -noupdate /tb/riscv/Mux1/b
add wave -noupdate /tb/riscv/Mux1/data_out
add wave -noupdate /tb/riscv/Mux2/sel
add wave -noupdate /tb/riscv/Mux2/a
add wave -noupdate /tb/riscv/Mux2/b
add wave -noupdate /tb/riscv/Mux2/data_out
add wave -noupdate /tb/riscv/Mux3/sel
add wave -noupdate /tb/riscv/Mux3/a
add wave -noupdate /tb/riscv/Mux3/b
add wave -noupdate /tb/riscv/Mux3/data_out
add wave -noupdate /tb/riscv/InsMem/Inst_Address
add wave -noupdate /tb/riscv/InsMem/Instruction
add wave -noupdate /tb/riscv/Ins/instruction
add wave -noupdate /tb/riscv/Ins/opcode
add wave -noupdate /tb/riscv/Ins/funct7
add wave -noupdate /tb/riscv/Ins/rd
add wave -noupdate /tb/riscv/Ins/rs1
add wave -noupdate /tb/riscv/Ins/rs2
add wave -noupdate /tb/riscv/Ins/funct3
add wave -noupdate /tb/riscv/CtrlUnit/Opcode
add wave -noupdate /tb/riscv/CtrlUnit/Branch
add wave -noupdate /tb/riscv/CtrlUnit/MemRead
add wave -noupdate /tb/riscv/CtrlUnit/MemtoReg
add wave -noupdate /tb/riscv/CtrlUnit/MemWrite
add wave -noupdate /tb/riscv/CtrlUnit/ALUSrc
add wave -noupdate /tb/riscv/CtrlUnit/RegWrite
add wave -noupdate /tb/riscv/CtrlUnit/ALUOp
add wave -noupdate /tb/riscv/RegFile/WriteData
add wave -noupdate /tb/riscv/RegFile/RS1
add wave -noupdate /tb/riscv/RegFile/RS2
add wave -noupdate /tb/riscv/RegFile/RD
add wave -noupdate /tb/riscv/RegFile/RegWrite
add wave -noupdate /tb/riscv/RegFile/clk
add wave -noupdate /tb/riscv/RegFile/reset
add wave -noupdate /tb/riscv/RegFile/ReadData1
add wave -noupdate /tb/riscv/RegFile/ReadData2
add wave -noupdate /tb/riscv/DataExtract/instruction
add wave -noupdate /tb/riscv/DataExtract/imm_data
add wave -noupdate /tb/riscv/ALUCtrl/ALUOp
add wave -noupdate /tb/riscv/ALUCtrl/Funct
add wave -noupdate /tb/riscv/ALUCtrl/Operation
add wave -noupdate /tb/riscv/ALU/a
add wave -noupdate /tb/riscv/ALU/b
add wave -noupdate /tb/riscv/ALU/ALUop
add wave -noupdate /tb/riscv/ALU/Result
add wave -noupdate /tb/riscv/ALU/ZERO
add wave -noupdate /tb/riscv/ALU/regRes
add wave -noupdate /tb/riscv/ALU/zer
add wave -noupdate /tb/riscv/DataMem/Mem_Addr
add wave -noupdate /tb/riscv/DataMem/Write_Data
add wave -noupdate /tb/riscv/DataMem/clk
add wave -noupdate /tb/riscv/DataMem/Mem_Write
add wave -noupdate /tb/riscv/DataMem/Mem_Read
add wave -noupdate /tb/riscv/DataMem/Read_Data
add wave -noupdate /tb/riscv/DataMem/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 209
configure wave -valuecolwidth 176
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {21205 ns}
